name: white_label
description: "white label project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  animated_segmented_tab_control: ^2.0.0
  pdf: ^3.6.0
  printing: ^5.1.0

  path_provider: ^2.0.11
  intl: ^0.19.0
  percent_indicator: ^4.0.1
  image_picker: ^0.8.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo_sukses.png
    - assets/topup.png
    - assets/qris.png
    - assets/topup1.png # This includes all assets in this folder
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
